import logging
from typing import Final, cast

from karppipeline.common import PipelineException
from karppipeline.execution.dependency import Dependency
from karppipeline.models import PipelineConfig
from karppipeline.modules.mink.install import mink_install, mink_uninstall
from karppipeline.modules.mink.mink_api import MinkAPI


"""
Add and install pre-run resources in Mink.
"""

__all__ = ["export", "install", "dependencies"]

logger = logging.getLogger(__name__)

MODULE_NAME: Final[str] = "mink"

dependencies = [Dependency("jsonl")]

install_dependencies = []


def export(*_args, **_kwargs):
    """
    This plugin does generate some configuration files, but since the files need
    the resource id created by Mink, the files are generated by install instead.
    """
    ...


def install(config: PipelineConfig, uninstall=False, instance=MODULE_NAME):
    mink_config = config.modules[instance]
    api_key: str = cast(str, mink_config.get("api_key", ""))
    if not api_key:
        raise PipelineException("Cannot use the Mink module without adding mink.api_key.")

    mink_api = MinkAPI(api_key)
    if not uninstall:
        mink_install(config, mink_api)
    else:
        mink_uninstall(config, mink_api)
