from karppipeline.execution.dependency import resolve_commands
from karppipeline.models import PipelineConfig


def install(config: PipelineConfig, subcommand: list[str] | None = None, uninstall=False) -> None:
    """
    install does not use the source files, only files already generated by run
    """

    resolved_cmds, mods = resolve_commands(config, subcommand, config.install, cmd_type="install")
    for cmd in resolved_cmds:
        mods[cmd].install(config, uninstall=uninstall, instance=cmd)


def uninstall(config: PipelineConfig, subcommand: list[str] | None = None) -> None:
    install(config, subcommand, uninstall=True)
