from karppipeline.execution.dependency import resolve_commands
from karppipeline.models import PipelineConfig


class BoolWrapper:
    def __init__(self):
        self.val = False

    def set(self, val: bool) -> None:
        self.val = val

    def __bool__(self) -> bool:
        return self.val


DRY_RUN = BoolWrapper()


def install(config: PipelineConfig, subcommand: list[str] | None = None, uninstall=False, dry_run=False) -> None:
    """
    install does not use the source files, only files already generated by run
    """

    # before running the install commands, set the DRY_RUN global variable, used to skip modifying operations in modules when True
    DRY_RUN.set(dry_run)

    resolved_cmds, mods = resolve_commands(config, subcommand, config.install, cmd_type="install")
    for cmd in resolved_cmds:
        mods[cmd].install(config, uninstall=uninstall, instance=cmd)


def uninstall(config: PipelineConfig, subcommand: list[str] | None = None, dry_run=False) -> None:
    install(config, subcommand, uninstall=True, dry_run=dry_run)
